version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=changMe
      - POSTGRES_PASSWORD=changeMe
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
